In [55]:
import numpy as np
from typing import Tuple, Literal

In [57]:
from utils import get_state_strings, convolve2d

In [58]:
sst4 = get_state_strings(4)
sst4

['0000',
 '0001',
 '0010',
 '0011',
 '0100',
 '0101',
 '0110',
 '0111',
 '1000',
 '1001',
 '1010',
 '1011',
 '1100',
 '1101',
 '1110',
 '1111']

In [59]:
c = [] # computational basis
for i, state in enumerate(sst4):
    c.append(np.array([int(s) for s in state]))

In [60]:
c

[array([0, 0, 0, 0]),
 array([0, 0, 0, 1]),
 array([0, 0, 1, 0]),
 array([0, 0, 1, 1]),
 array([0, 1, 0, 0]),
 array([0, 1, 0, 1]),
 array([0, 1, 1, 0]),
 array([0, 1, 1, 1]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 1]),
 array([1, 0, 1, 0]),
 array([1, 0, 1, 1]),
 array([1, 1, 0, 0]),
 array([1, 1, 0, 1]),
 array([1, 1, 1, 0]),
 array([1, 1, 1, 1])]

In [61]:
g= [
    ((c[sst4.index("0000")] + c[sst4.index("0101")] + c[sst4.index("1010")] + c[sst4.index("1111")])/2).astype(int),
    ((c[sst4.index("0000")] + c[sst4.index("0101")] - c[sst4.index("1010")] - c[sst4.index("1111")])/2).astype(int),
    ((c[sst4.index("0000")] - c[sst4.index("0101")] + c[sst4.index("1010")] - c[sst4.index("1111")])/2).astype(int),
    ((c[sst4.index("0000")] - c[sst4.index("0101")] - c[sst4.index("1010")] + c[sst4.index("1111")])/2).astype(int),
    
    ((c[sst4.index("0001")] + c[sst4.index("0100")] + c[sst4.index("1011")] + c[sst4.index("1110")])/2).astype(int),
    ((c[sst4.index("0001")] + c[sst4.index("0100")] - c[sst4.index("1011")] - c[sst4.index("1110")])/2).astype(int),
    ((c[sst4.index("0001")] - c[sst4.index("0100")] + c[sst4.index("1011")] - c[sst4.index("1110")])/2).astype(int),
    ((c[sst4.index("0001")] - c[sst4.index("0100")] - c[sst4.index("1011")] + c[sst4.index("1110")])/2).astype(int),
    
    ((c[sst4.index("0010")] + c[sst4.index("0111")] + c[sst4.index("1000")] + c[sst4.index("1101")])/2).astype(int),
    ((c[sst4.index("0010")] + c[sst4.index("0111")] - c[sst4.index("1000")] - c[sst4.index("1101")])/2).astype(int),
    ((c[sst4.index("0010")] - c[sst4.index("0111")] + c[sst4.index("1000")] - c[sst4.index("1101")])/2).astype(int),
    ((c[sst4.index("0010")] - c[sst4.index("0111")] - c[sst4.index("1000")] + c[sst4.index("1101")])/2).astype(int),
    
    ((c[sst4.index("0011")] + c[sst4.index("0110")] + c[sst4.index("1001")] + c[sst4.index("1100")])/2).astype(int),
    ((c[sst4.index("0011")] + c[sst4.index("0110")] - c[sst4.index("1001")] - c[sst4.index("1100")])/2).astype(int),
    ((c[sst4.index("0011")] - c[sst4.index("0110")] + c[sst4.index("1001")] - c[sst4.index("1100")])/2).astype(int),
    ((c[sst4.index("0011")] - c[sst4.index("0110")] - c[sst4.index("1001")] + c[sst4.index("1100")])/2).astype(int),
]

In [62]:
g[0]

array([1, 1, 1, 1])

In [63]:
c

[array([0, 0, 0, 0]),
 array([0, 0, 0, 1]),
 array([0, 0, 1, 0]),
 array([0, 0, 1, 1]),
 array([0, 1, 0, 0]),
 array([0, 1, 0, 1]),
 array([0, 1, 1, 0]),
 array([0, 1, 1, 1]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 1]),
 array([1, 0, 1, 0]),
 array([1, 0, 1, 1]),
 array([1, 1, 0, 0]),
 array([1, 1, 0, 1]),
 array([1, 1, 1, 0]),
 array([1, 1, 1, 1])]

In [64]:
convention = ["0000","0001","0010","0100",
              "1000","0011","0110","1100",
              "0101","1001","1010","0111",
              "1011","1101","1110","1111"]
index_map = [sst4.index(s) for s in convention]
index_map

[0, 1, 2, 4, 8, 3, 6, 12, 5, 9, 10, 7, 11, 13, 14, 15]

$$\sum_i^{16} |c_{f(i)} \rangle \langle g_{i}|$$

In [81]:
M = np.zeros((2**4, 2**4))
for i, gi in enumerate(g):
    M[i][index_map[i]] = 1
M = M.astype(int)


In [84]:
M

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [6]:
N=6

In [7]:
from math import sqrt

In [8]:
1/sqrt(2**N)

0.125

In [9]:
2**(-N)

0.015625